version: "3"
services:
  api:
    build: .
    ports:
      - 8000:8000
    networks:
      - ecom-network
    volumes:
      - ./:/usr/src/app
    # env_file:
    #     - ./.env
    environment:
      - DATABASE_HOSTNAME=postgres
      - DATABASE_PORT=5432
      - DATABASE_PASSWORD=password123
      - DATABASE_NAME=ecom-db
      - DATABASE_USERNAME=postgres
      - SECRET_KEY=09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - postgres
#    links:
#      - postgres

  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=ecom-db
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5430:5432'
    networks:
      - ecom-network
    volumes:
      - postgres-db:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - ./db/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh

networks:
    ecom-network:
        driver: bridge

volumes:
  postgres-db:
#volumes:
#  postgres-db:
#    driver: local
